# Generated by Django 4.2.26 on 2025-11-25 20:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "is_secret",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this area is hidden from public view (secret/illegal climbing spots)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Areas",
                "ordering": ["city", "name"],
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Latitude coordinate for map positioning",
                        max_digits=9,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Longitude coordinate for map positioning",
                        max_digits=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        help_text="Area this sector belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="boulders.area",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sectors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sectors",
                "ordering": ["area", "name"],
                "unique_together": {("area", "name")},
            },
        ),
        migrations.CreateModel(
            name="Wall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_walls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        help_text="Sector this wall belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walls",
                        to="boulders.sector",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Walls",
                "ordering": ["sector", "name"],
                "unique_together": {("sector", "name")},
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BoulderProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "name_normalized",
                    models.CharField(
                        db_index=True,
                        help_text="Normalized version of name (lowercase, no diacritics) for safe lookups",
                        max_length=200,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("3", "3"),
                            ("3+", "3+"),
                            ("4", "4"),
                            ("4+", "4+"),
                            ("5", "5"),
                            ("5+", "5+"),
                            ("6A", "6A"),
                            ("6A+", "6A+"),
                            ("6B", "6B"),
                            ("6B+", "6B+"),
                            ("6C", "6C"),
                            ("6C+", "6C+"),
                            ("7A", "7A"),
                            ("7A+", "7A+"),
                            ("7B", "7B"),
                            ("7B+", "7B+"),
                            ("7C", "7C"),
                            ("7C+", "7C+"),
                            ("8A", "8A"),
                            ("8A+", "8A+"),
                            ("8B", "8B"),
                            ("8B+", "8B+"),
                            ("8C", "8C"),
                            ("8C+", "8C+"),
                            ("9A", "9A"),
                            ("9A+", "9A+"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "external_links",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of external links with 'label' and 'url' fields. Example: [{'label': '8a.nu', 'url': 'https://...'}]",
                    ),
                ),
                (
                    "video_links",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of video links (YouTube, Vimeo, etc.) with 'label' and 'url' fields. Example: [{'label': 'Send Video', 'url': 'https://youtube.com/...'}]",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Star rating from 1 to 5 (e.g., 1.0, 2.5, 5.0)",
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        help_text="Area this problem belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="boulders.area",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Author/establisher of this boulder problem",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_problems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_problems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Sector this problem belongs to. Required if wall is not specified.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="boulders.sector",
                    ),
                ),
                (
                    "wall",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Wall/sub-sector this problem belongs to. If specified, sector must match wall.sector.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="problems",
                        to="boulders.wall",
                    ),
                ),
            ],
            options={
                "ordering": ["area", "sector", "wall", "name"],
            },
        ),
        migrations.CreateModel(
            name="BoulderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="boulder_images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary image for a sector (if sector is specified). This flag only affects sector-level image ordering and display. For images linked to problems via ProblemLine, this flag is ignored.",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Sector this image belongs to. Images can also be shared across problems via ProblemLine.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="boulders.sector",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="area",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="City/area where this climbing area is located",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="areas",
                to="boulders.city",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_areas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ProblemLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(
                        default=list,
                        help_text="Array of coordinate points. Each point has 'x' and 'y' (0-1 normalized). Example: [{'x': 0.2, 'y': 0.3}, {'x': 0.8, 'y': 0.7}]",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#FF0000",
                        help_text="Hex color code for the line (e.g., #FF0000)",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Image containing this problem line",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_lines",
                        to="boulders.boulderimage",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        help_text="Problem this line represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_lines",
                        to="boulders.boulderproblem",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("image", "problem")},
            },
        ),
        migrations.AddIndex(
            model_name="boulderproblem",
            index=models.Index(
                fields=["area", "name_normalized"],
                name="boulders_bo_area_id_bcc025_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="boulderproblem",
            index=models.Index(
                fields=["sector", "name_normalized"],
                name="boulders_bo_sector__4eaf89_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boulderproblem",
            unique_together={("area", "name")},
        ),
    ]
