# Generated by Django 4.2.26 on 2025-11-18 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boulders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boulder",
            options={"ordering": ["crag", "name"]},
        ),
        migrations.AlterField(
            model_name="boulder",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Optional: Boulder-specific latitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Optional: Boulder-specific longitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Crag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Latitude coordinate for map positioning",
                        max_digits=9,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Longitude coordinate for map positioning",
                        max_digits=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_crags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="boulder",
            name="crag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boulders",
                to="boulders.crag",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boulder",
            unique_together={("crag", "name")},
        ),
    ]
