# Generated by Django 4.2.26 on 2025-11-26 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boulders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boulderproblem",
            name="author_name",
            field=models.CharField(
                blank=True,
                help_text="Author name as string (used when author is not a Django User)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="boulderproblem",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Author/establisher of this boulder problem (Django User if exists)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_problems",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
