# Generated by Django 4.2.26 on 2025-11-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulders", "0002_boulderproblem_author_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="polygon_boundary",
            field=models.JSONField(
                blank=True,
                help_text="Array of [lat, lng] coordinate pairs defining the sector boundary polygon. Example: [[49.4, 16.7], [49.401, 16.7], [49.401, 16.701], [49.4, 16.701]]",
                null=True,
            ),
        ),
    ]
