# Generated by Django 4.2.26 on 2025-12-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulders", "0004_add_is_secret_to_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="name_normalized",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Normalized version of name (lowercase, no diacritics) for safe lookups",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="name_normalized",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Normalized version of name (lowercase, no diacritics) for safe lookups",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="name_normalized",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Normalized version of name (lowercase, no diacritics) for safe lookups",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="wall",
            name="name_normalized",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Normalized version of name (lowercase, no diacritics) for safe lookups",
                max_length=200,
            ),
        ),
    ]
