# Generated by Django 4.2.26 on 2025-11-18 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boulders", "0004_restructure_remove_boulder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crag",
            options={"ordering": ["city", "name"]},
        ),
        migrations.AlterField(
            model_name="boulderproblem",
            name="grade",
            field=models.CharField(
                choices=[
                    ("3", "3"),
                    ("3+", "3+"),
                    ("4", "4"),
                    ("4+", "4+"),
                    ("5", "5"),
                    ("5+", "5+"),
                    ("6A", "6A"),
                    ("6A+", "6A+"),
                    ("6B", "6B"),
                    ("6B+", "6B+"),
                    ("6C", "6C"),
                    ("6C+", "6C+"),
                    ("7A", "7A"),
                    ("7A+", "7A+"),
                    ("7B", "7B"),
                    ("7B+", "7B+"),
                    ("7C", "7C"),
                    ("7C+", "7C+"),
                    ("8A", "8A"),
                    ("8A+", "8A+"),
                    ("8B", "8B"),
                    ("8B+", "8B+"),
                    ("8C", "8C"),
                    ("8C+", "8C+"),
                    ("9A", "9A"),
                    ("9A+", "9A+"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="boulderproblem",
            name="wall",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Wall/sector within the crag",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="problems",
                to="boulders.wall",
            ),
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="crag",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="City/area where this crag is located",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crags",
                to="boulders.city",
            ),
        ),
    ]
