# Generated by Django 4.2.26 on 2025-11-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulders", "0005_alter_crag_options_alter_boulderproblem_grade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boulderproblem",
            name="external_links",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of external links with 'label' and 'url' fields. Example: [{'label': '8a.nu', 'url': 'https://...'}]",
            ),
        ),
        migrations.AddField(
            model_name="boulderproblem",
            name="video_links",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of video links (YouTube, Vimeo, etc.) with 'label' and 'url' fields. Example: [{'label': 'Send Video', 'url': 'https://youtube.com/...'}]",
            ),
        ),
    ]
