# Generated by Django 4.2.26 on 2025-12-22 13:55

from django.db import migrations
from boulders.utils import normalize_problem_name


def populate_name_normalized(apps, schema_editor):
    """Populate name_normalized field for all existing records"""
    City = apps.get_model("boulders", "City")
    Area = apps.get_model("boulders", "Area")
    Sector = apps.get_model("boulders", "Sector")
    Wall = apps.get_model("boulders", "Wall")

    for city in City.objects.all():
        if city.name:
            city.name_normalized = normalize_problem_name(city.name)
            city.save(update_fields=["name_normalized"])

    for area in Area.objects.all():
        if area.name:
            area.name_normalized = normalize_problem_name(area.name)
            area.save(update_fields=["name_normalized"])

    for sector in Sector.objects.all():
        if sector.name:
            sector.name_normalized = normalize_problem_name(sector.name)
            sector.save(update_fields=["name_normalized"])

    for wall in Wall.objects.all():
        if wall.name:
            wall.name_normalized = normalize_problem_name(wall.name)
            wall.save(update_fields=["name_normalized"])


def reverse_populate_name_normalized(apps, schema_editor):
    """Reverse migration - clear name_normalized field"""
    City = apps.get_model("boulders", "City")
    Area = apps.get_model("boulders", "Area")
    Sector = apps.get_model("boulders", "Sector")
    Wall = apps.get_model("boulders", "Wall")

    City.objects.all().update(name_normalized="")
    Area.objects.all().update(name_normalized="")
    Sector.objects.all().update(name_normalized="")
    Wall.objects.all().update(name_normalized="")


class Migration(migrations.Migration):

    dependencies = [
        ("boulders", "0005_add_name_normalized_to_models"),
    ]

    operations = [
        migrations.RunPython(
            populate_name_normalized, reverse_populate_name_normalized
        ),
    ]
