# Generated by Django 4.2.26 on 2025-11-19 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boulders", "0006_boulderproblem_external_links_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(
                        default=list,
                        help_text="Array of coordinate points. Each point has 'x' and 'y' (0-1 normalized). Example: [{'x': 0.2, 'y': 0.3}, {'x': 0.8, 'y': 0.7}]",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#FF0000",
                        help_text="Hex color code for the line (e.g., #FF0000)",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Image containing this problem line",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_lines",
                        to="boulders.boulderimage",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        help_text="Problem this line represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_lines",
                        to="boulders.boulderproblem",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("image", "problem")},
            },
        ),
    ]
