# Generated by Django 4.2.26 on 2025-12-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulders", "0006_populate_name_normalized"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boulderproblem",
            name="name_normalized",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Normalized version of name (lowercase, no diacritics) for safe lookups",
                max_length=200,
            ),
        ),
    ]
