# Generated by Django 4.2.26 on 2025-11-19 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boulders", "0007_problemline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boulderimage",
            name="problem",
        ),
        migrations.AlterField(
            model_name="boulderimage",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Primary image for a wall (if wall is specified). For shared images, this is ignored.",
            ),
        ),
        migrations.AlterField(
            model_name="boulderimage",
            name="wall",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Wall this image belongs to. Images can also be shared across problems via ProblemLine.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="boulders.wall",
            ),
        ),
    ]
