# Generated by Django 4.2.26 on 2025-12-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulders", "0007_unify_name_normalized_with_mixin"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="radius_meters",
            field=models.DecimalField(
                decimal_places=2,
                default=100.0,
                help_text="Radius in meters for the circular sector boundary. Used by frontend to generate circle polygon.",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="sector",
            name="polygon_boundary",
            field=models.JSONField(
                blank=True,
                help_text="Array of [lat, lng] coordinate pairs defining the sector boundary polygon. If not set, frontend will generate a circle from latitude, longitude, and radius_meters. Example: [[49.4, 16.7], [49.401, 16.7], [49.401, 16.701], [49.4, 16.701]]",
                null=True,
            ),
        ),
    ]
