# Generated by Django 4.2.26 on 2025-11-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulders", "0008_remove_problem_fk_from_boulderimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boulderimage",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Primary image for a wall (if wall is specified). This flag only affects wall-level image ordering and display. For images linked to problems via ProblemLine, this flag is ignored.",
            ),
        ),
    ]
