# Generated by Django 4.2.26 on 2025-12-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulders", "0008_add_radius_meters_to_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude coordinate for map positioning",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude coordinate for map positioning",
                max_digits=9,
                null=True,
            ),
        ),
    ]
