# Generated by Django 4.2.26 on 2025-11-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulders", "0009_alter_boulderimage_is_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="boulderproblem",
            name="name_normalized",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Normalized version of name (lowercase, no diacritics) for safe lookups",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="boulderproblem",
            index=models.Index(
                fields=["crag", "name_normalized"],
                name="boulders_bo_crag_id_b9193d_idx",
            ),
        ),
    ]
