# Generated by Django 4.2.26 on 2025-11-20 16:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boulders", "0012_make_name_normalized_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="boulderproblem",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Author/establisher of this boulder problem",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_problems",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="boulderproblem",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Star rating from 1 to 5 (e.g., 1.0, 2.5, 5.0)",
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
