# Generated by Django 4.2.26 on 2025-11-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boulders", "0013_add_rating_and_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="crag",
            name="is_secret",
            field=models.BooleanField(
                default=False,
                help_text="If True, this crag is hidden from public view (secret/illegal climbing spots)",
            ),
        ),
    ]
