# Generated by Django 4.2.26 on 2025-11-25 20:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boulders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, max_length=500)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boulders.boulderproblem",
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="UserList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problems",
                    models.ManyToManyField(
                        related_name="user_lists",
                        through="lists.ListEntry",
                        to="boulders.boulderproblem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="listentry",
            name="user_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lists.userlist"
            ),
        ),
        migrations.CreateModel(
            name="Tick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date when the problem was completed"),
                ),
                ("notes", models.TextField(blank=True, max_length=500)),
                (
                    "tick_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("3", "3"),
                            ("3+", "3+"),
                            ("4", "4"),
                            ("4+", "4+"),
                            ("5", "5"),
                            ("5+", "5+"),
                            ("6A", "6A"),
                            ("6A+", "6A+"),
                            ("6B", "6B"),
                            ("6B+", "6B+"),
                            ("6C", "6C"),
                            ("6C+", "6C+"),
                            ("7A", "7A"),
                            ("7A+", "7A+"),
                            ("7B", "7B"),
                            ("7B+", "7B+"),
                            ("7C", "7C"),
                            ("7C+", "7C+"),
                            ("8A", "8A"),
                            ("8A+", "8A+"),
                            ("8B", "8B"),
                            ("8B+", "8B+"),
                            ("8C", "8C"),
                            ("8C+", "8C+"),
                            ("9A", "9A"),
                            ("9A+", "9A+"),
                        ],
                        help_text="The actual grade you climbed (may differ from problem grade if you used easier beta)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "suggested_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("3", "3"),
                            ("3+", "3+"),
                            ("4", "4"),
                            ("4+", "4+"),
                            ("5", "5"),
                            ("5+", "5+"),
                            ("6A", "6A"),
                            ("6A+", "6A+"),
                            ("6B", "6B"),
                            ("6B+", "6B+"),
                            ("6C", "6C"),
                            ("6C+", "6C+"),
                            ("7A", "7A"),
                            ("7A+", "7A+"),
                            ("7B", "7B"),
                            ("7B+", "7B+"),
                            ("7C", "7C"),
                            ("7C+", "7C+"),
                            ("8A", "8A"),
                            ("8A+", "8A+"),
                            ("8B", "8B"),
                            ("8B+", "8B+"),
                            ("8C", "8C"),
                            ("8C+", "8C+"),
                            ("9A", "9A"),
                            ("9A+", "9A+"),
                        ],
                        help_text="User's suggested grade for this problem (optional)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="User's star rating for this problem (1-5 stars, optional)",
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticks",
                        to="boulders.boulderproblem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "unique_together": {("user", "problem")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="listentry",
            unique_together={("user_list", "problem")},
        ),
    ]
