# Generated by Django 4.2.26 on 2025-12-12 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listentry",
            name="user_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listentry_set",
                to="lists.userlist",
            ),
        ),
    ]
