# Generated by Django 4.2.26 on 2025-11-20 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_tick_suggested_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="tick",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="User's star rating for this problem (1-5 stars, optional)",
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
