# Generated by Django 4.2.26 on 2025-11-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_add_rating_to_tick"),
    ]

    operations = [
        migrations.AddField(
            model_name="tick",
            name="tick_grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("3", "3"),
                    ("3+", "3+"),
                    ("4", "4"),
                    ("4+", "4+"),
                    ("5", "5"),
                    ("5+", "5+"),
                    ("6A", "6A"),
                    ("6A+", "6A+"),
                    ("6B", "6B"),
                    ("6B+", "6B+"),
                    ("6C", "6C"),
                    ("6C+", "6C+"),
                    ("7A", "7A"),
                    ("7A+", "7A+"),
                    ("7B", "7B"),
                    ("7B+", "7B+"),
                    ("7C", "7C"),
                    ("7C+", "7C+"),
                    ("8A", "8A"),
                    ("8A+", "8A+"),
                    ("8B", "8B"),
                    ("8B+", "8B+"),
                    ("8C", "8C"),
                    ("8C+", "8C+"),
                    ("9A", "9A"),
                    ("9A+", "9A+"),
                ],
                help_text="The actual grade you climbed (may differ from problem grade if you used easier beta)",
                max_length=10,
                null=True,
            ),
        ),
    ]
