# Generated by Django 4.2.26 on 2025-11-25 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "height",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("<150", "<150 cm"),
                            ("150-155", "150-155 cm"),
                            ("155-160", "155-160 cm"),
                            ("160-165", "160-165 cm"),
                            ("165-170", "165-170 cm"),
                            ("170-175", "170-175 cm"),
                            ("175-180", "175-180 cm"),
                            ("180-185", "180-185 cm"),
                            ("185-190", "185-190 cm"),
                            ("190-195", "190-195 cm"),
                            (">195", ">195 cm"),
                        ],
                        help_text="Height category in centimeters",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "ape_index",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Ape index (wingspan - height) in centimeters. Positive means longer wingspan.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
