# Generated by Django 4.2.26 on 2025-11-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ape_index",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ape index (wingspan - height) in centimeters. Positive means longer wingspan.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="height",
            field=models.CharField(
                blank=True,
                choices=[
                    ("<150", "<150 cm"),
                    ("150-155", "150-155 cm"),
                    ("155-160", "155-160 cm"),
                    ("160-165", "160-165 cm"),
                    ("165-170", "165-170 cm"),
                    ("170-175", "170-175 cm"),
                    ("175-180", "175-180 cm"),
                    ("180-185", "180-185 cm"),
                    ("185-190", "185-190 cm"),
                    ("190-195", "190-195 cm"),
                    (">195", ">195 cm"),
                ],
                help_text="Height category in centimeters",
                max_length=10,
                null=True,
            ),
        ),
    ]
